version: "2"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    environment:
      - SITE_UP_CHECKER_SETTINGS=/usr/src/app/prd_settings.py
    command: gunicorn -k gevent -b 0.0.0.0:8070 site_up_checker.application:app
    depends_on:
      - redis
    ports:
      - "8070:8070"
  celery:
    build:
      context: .
      dockerfile: Dockerfile-celery
    environment:
      - SITE_UP_CHECKER_SETTINGS=/usr/src/app/prd_settings.py
    command: celery -A site_up_checker.application:celery worker -B -n site_up_checker.%h

  redis:
    image: redis
  rabbitmq:
    image: rabbitmq
