FROM python:2.7-onbuild
FROM ubuntu:16.04

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update --fix-missing
RUN apt-get install -y apt-utils gunicorn python-gevent nodejs curl apt-transport-https python-pip

RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
RUN . ~/.nvm/nvm.sh ; nvm install v4.8.0

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - ;\
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list ;\
    apt-get update ;\
    apt-get install -y yarn ;\
    yarn install --modules-folder site_up_checker/frontend/static/libs

RUN yarn

COPY . /usr/src/app

RUN cd /usr/src/app ; pip install --upgrade pip ; pip install -r requirements.txt

WORKDIR /usr/src/app
EXPOSE 8070
