FROM ubuntu:16.04

RUN apt-get update --fix-missing 
RUN apt-get install -y build-essential

# python reuirements
COPY requirements.txt .
RUN apt-get install -y python-pip ;\
    pip install --upgrade pip ;\
    pip install --no-cache -r requirements.txt

RUN mkdir -p /usr/src/app

# dependencies
RUN mkdir -p /deps

COPY . /usr/src/app
WORKDIR /usr/src/app
